server:
  port: 10100

spring:
  application:
    name: cloud-register
  security:
    user:
      name: amoe
      password: amoe
      roles: ADMIN
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
    renewal-threshold-update-interval-ms: 900000
    delta-retention-timer-interval-in-ms: 30000
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
